name: swarmui
channels:
  - conda-forge
  - defaults
dependencies:
  - dotnet-sdk=8.0.408          # .NET 8 SDK for SwarmUI
  - dotnet-runtime=8.0.15       # .NET 8 Runtime
  - dotnet-aspnetcore=8.0.15    # ASP.NET Core Runtime (required for SwarmUI)
  - python=3.11                 # Minimal Python for integration scripts
  - pip
  - git
  - curl
  - wget
  - ca-certificates
  - openssl
  - pip:
    - requests          # For API integration scripts
    - pillow            # Image processing utilities
    - numpy             # Numerical operations
    - aiohttp           # Async HTTP client
    - websockets        # WebSocket support
    - psutil            # System utilities
